services:
    wirecard.payment_manager.default:
        class: %wirecard.payment.manager.class%
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
            - %wirecard.payment.request.class%
            - %wirecard.payment.response.class%
    wirecard.twig.extension:
        class: DomUdall\WirecardBundle\Twig\WirecardTwigExtension
        arguments: [@service_container]
        tags:
            -  { name: twig.extension }