language: php

php:
  - 5.3
  #- 5.4

env:
  - SYMFONY_VERSION=v2.0.0
  - SYMFONY_VERSION=v2.0.1
  - SYMFONY_VERSION=v2.0.3
  - SYMFONY_VERSION=v2.0.4
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=v2.0.6
  - SYMFONY_VERSION=v2.0.7
  - SYMFONY_VERSION=v2.0.8
  - SYMFONY_VERSION=v2.0.9
  - SYMFONY_VERSION=v2.0.10
  - SYMFONY_VERSION=origin/master

before_script: php vendor/vendors.php